# Download data configuration
excel_file: ECG-AI.xlsx
sheet_name: All
sasToken: ?sp=r&st=2024-06-24T07:27:43Z&se=2024-07-05T15:27:43Z&spr=https&sv=2022-11-02&sr=c&sig=nu2ryh5dxKfU6fDoq20%2BPG%2BASbFYPE4lKhhc4xy39Qc%3D
base_url: https://wellnestprodstorage.blob.core.windows.net/ecg-recordings/
output_csv: data/ecg_data_1.csv
start_index: 2          # It must start from index 2.
end_index: 10


# Inference configuration
test_data_filepath: test_dataset.csv
model_filepath: best_acc.keras
normal_diseases:
  - NO SIGNIFICANT ABNORMALITIES DETECTED
  - SINUS RHYTHM
  - WITHIN NORMAL LIMITS

# API configuration
MODEL_PATH: /home/algoryc/Documents/ecg-weights

# Training configuration
directory: data
dataset_files: ["ecg_data_1.csv", "ecg_data_2.csv", "ecg_data_3.csv", "ecg_data_4.csv", "ecg_data_5.csv", "ecg_data_6.csv"]    # If you have only 1 file, just add that 1 file in list
epochs: 20
batch_size: 4