# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wellnest-ai-ecg

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1a23677ffa054ed38c1afa23f6d52928 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8ff0f2a9fae04ed4aa8ffd4c544e594a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1a23677ffa054ed38c1afa23f6d52928 }}/wellnest/wellnest-ai-ecg:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wellnest-ai-ecg'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eca2033337a341c38c18a26b4e7e1d06 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1a23677ffa054ed38c1afa23f6d52928 }}/wellnest/wellnest-ai-ecg:${{ github.sha }}'